# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ARM-Datacenter

logo: "assets/images/futurewei-logo-swirl-200x57.png"

email:
description: >- # this means to ignore newlines until "baseurl:"
  The ARM-Datacenter blog includes articles on QEMU, Linux kernel scheduler and other ongoing projects.
  Our goal is to create and contribute to Software infrastructure that simplifies adoption of ARM based hardware in a Datacenter environment.
  
name: ARM-Datacenter blog
#twitter_username: username
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Futurewei"
  avatar : "/assets/images/Futurewei-bio-photo.png"
  bio    : "Shaping the Future Towards a Fully Connected, Intelligent World."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.futurewei.com"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.futurewei.com"
    - label: "RSS"
      icon: "fas fa-fw fa-rss"
      url: "/feed.xml"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
